from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import telegram  # For sending alerts

# Set up Telegram bot (Replace with your own bot token & chat ID)
TELEGRAM_BOT_TOKEN = "http://t.me/cskrcbthala_bot"
TELEGRAM_CHAT_ID = "1725170783"

def send_telegram_alert(message):
    bot = telegram.Bot(token=TELEGRAM_BOT_TOKEN)
    bot.send_message(chat_id=TELEGRAM_CHAT_ID, text=message)

# Configure Selenium WebDriver (Headless Mode for GitHub Actions)
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

# Start WebDriver
driver = webdriver.Chrome(options=options)
driver.get("https://link.district.in/DSTRKT/hyj25jcj")  # Replace with actual ticket page URL

time.sleep(3)  # Wait for page to load

# Log in to the District app
driver.find_element(By.NAME, "mahimadarshi@gmail.com").send_keys("mahimadarshi@gmail.com")
driver.find_element(By.NAME, "Mahi@768").send_keys("Mahi@768", Keys.RETURN)

time.sleep(5)  # Allow login to complete

# Navigate to CSK vs RCB ticket page
driver.get("https://link.district.in/DSTRKT/hyj25jcj")  # Replace with actual URL

while True:
    try:
        # Check if "Book Now" button is available
        book_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Book Now')]")
        if book_button.is_displayed():
            send_telegram_alert("🚨 IPL Tickets Available! Go to District app NOW!")
            print("Tickets are live! Sending alert...")
            break
    except:
        print("Tickets not available yet. Retrying...")
    
    time.sleep(10)  # Check every 10 seconds

# Stop at payment for manual entry
print("Stopping at payment step for manual checkout.")

# Close the browser
driver.quit()

